name: Build and Push Images

on:
  push:
    branches: [main]
    paths:
      - 'images/**'
      - 'harness/**'
      - 'Dockerfile'
      - 'cmd/**'
      - 'internal/**'
      - 'api/**'
      - 'go.mod'
      - 'go.sum'
  pull_request:
    paths:
      - 'images/**'
      - 'harness/**'
      - 'Dockerfile'
      - 'cmd/**'
      - 'internal/**'
      - 'api/**'
      - 'go.mod'
      - 'go.sum'
  workflow_dispatch: {}

permissions: {}

jobs:
  controller-agent:
    permissions:
      contents: read
    name: Build controller agent image
    runs-on: ubuntu-latest
    steps:
      - name: Clone the code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: Build image
        run: make controller-agent-build

      - name: Log in to Quay.io
        if: github.event_name != 'pull_request'
        uses: docker/login-action@74a5d142397b4f367a81961eba4e8cd7edddf772 # v3.4.0
        with:
          registry: quay.io
          username: ${{ vars.QUAY_USERNAME }}
          password: ${{ secrets.QUAY_PASSWORD }}

      - name: Push image
        if: github.event_name != 'pull_request'
        run: make controller-agent-push

  agent-images:
    permissions:
      contents: read
    name: Build stage agent images
    runs-on: ubuntu-latest
    steps:
      - name: Clone the code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: Build images
        run: make agent-images-build

      - name: Log in to Quay.io
        if: github.event_name != 'pull_request'
        uses: docker/login-action@74a5d142397b4f367a81961eba4e8cd7edddf772 # v3.4.0
        with:
          registry: quay.io
          username: ${{ vars.QUAY_USERNAME }}
          password: ${{ secrets.QUAY_PASSWORD }}

      - name: Push images
        if: github.event_name != 'pull_request'
        run: make agent-images-push

  controller:
    permissions:
      contents: read
    name: Build controller image
    runs-on: ubuntu-latest
    steps:
      - name: Clone the code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: Build image
        run: make docker-build

      - name: Log in to Quay.io
        if: github.event_name != 'pull_request'
        uses: docker/login-action@74a5d142397b4f367a81961eba4e8cd7edddf772 # v3.4.0
        with:
          registry: quay.io
          username: ${{ vars.QUAY_USERNAME }}
          password: ${{ secrets.QUAY_PASSWORD }}

      - name: Push image
        if: github.event_name != 'pull_request'
        run: make docker-push
